# Generated by Django 5.2.1 on 2025-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_safeproduct_description_alter_safeproduct_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeproduct',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
