# Generated by Django 5.2.1 on 2025-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_safeproduct_is_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeproduct',
            name='category',
            field=models.CharField(choices=[('home_commercial', 'Home/Commercial'), ('cabinet', 'Cabinet'), ('fireproof', 'Fireproof'), ('wall', 'Wall')], default='home_commercial', max_length=50),
        ),
    ]
