# Generated by Django 5.2.1 on 2025-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_safeproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
