# Generated by Django 5.2.1 on 2025-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_safeproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeproduct',
            name='category',
            field=models.CharField(choices=[('home_commercial', 'Home/Commercial'), ('cabinet', 'Cabinet'), ('wall', 'Wall')], default='home_commercial', max_length=50),
        ),
    ]
