# Generated by Django 5.2.1 on 2025-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_cartitem_orderitem_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeproduct',
            name='category',
            field=models.CharField(choices=[('home', 'Home/Commercial'), ('cabinet', 'Cabinet'), ('wall', 'Wall')], default='home_commercial', max_length=50),
        ),
    ]
