# Generated by Django 5.2.1 on 2025-06-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_order_number_order_user'),
    ]

    operations = [
    ]
