# Generated by Django 5.2.1 on 2025-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeproduct',
            name='category',
            field=models.CharField(choices=[('home_commercial', 'Home/Commercial'), ('cabinet', 'Cabinet'), ('wall', 'Wall')], default='home', max_length=50),
        ),
    ]
