# Generated by Django 5.2.1 on 2025-06-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_safeproduct_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
