# Generated by Django 5.2.1 on 2025-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeproduct',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('cabinet', 'Cabinet'), ('wall', 'Wall')], default='home', max_length=50),
        ),
    ]
