# Generated by Django 5.2.1 on 2025-06-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_safeproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an icon for this specification (e.g., SVG)', null=True, upload_to='spec_icons/'),
        ),
    ]
