# Generated by Django 5.2.1 on 2025-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productspecification_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='icon',
            field=models.CharField(blank=True, choices=[('anti-theft.svg', 'anti-theft.svg'), ('lock.svg', 'lock.svg'), ('truck.svg', 'truck.svg'), ('digital.svg', 'digital.svg'), ('fireproof.svg', 'fireproof.svg'), ('fire.svg', 'fire.svg'), ('water.svg', 'water.svg'), ('key.svg', 'key.svg'), ('ruler.svg', 'ruler.svg'), ('weight.svg', 'weight.svg'), ('dollar-sign.svg', 'dollar-sign.svg'), ('shield.svg', 'shield.svg')], help_text='Select an icon from the available options.', max_length=100, null=True),
        ),
    ]
