# Generated by Django 5.2.1 on 2025-06-18 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productspecification_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='icon',
            field=models.CharField(blank=True, choices=[('dimensions.svg', 'dimensions.svg'), ('anti-theft.svg', 'anti-theft.svg'), ('lock.svg', 'lock.svg'), ('capacity.svg', 'capacity.svg'), ('truck.svg', 'truck.svg'), ('digital.svg', 'digital.svg'), ('fireproof.svg', 'fireproof.svg'), ('fire.svg', 'fire.svg'), ('water.svg', 'water.svg'), ('key.svg', 'key.svg'), ('ruler.svg', 'ruler.svg'), ('weight.svg', 'weight.svg'), ('dollar-sign.svg', 'dollar-sign.svg'), ('shield.svg', 'shield.svg')], help_text='Select an icon from the available options.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='safeproduct',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('cabinet', 'Cabinet'), ('wall', 'Wall')], db_index=True, default='home', max_length=50),
        ),
        migrations.AlterField(
            model_name='safeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='safeproduct',
            name='is_in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='safeproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number', 'contact_email', 'contact_phone'], name='store_order_order_n_120b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='store_order_order_i_ec571c_idx'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['name'], name='store_produ_name_3ca853_idx'),
        ),
        migrations.AddIndex(
            model_name='safeproduct',
            index=models.Index(fields=['name', 'is_in_stock', 'created_at', 'category'], name='store_safep_name_999ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='storelocation',
            index=models.Index(fields=['name', 'is_primary'], name='store_store_name_8fb9de_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['added_at'], name='store_wishl_added_a_ec16e0_idx'),
        ),
    ]
