# Generated by Django 5.2.1 on 2025-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short description of the team member', max_length=500)),
                ('image', models.ImageField(blank=True, default='team/default.jpg', upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower number first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this team member on the website')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
