# Generated by Django 5.2.1 on 2025-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Used in URLs, e.g., 'home-security'", unique=True)),
                ('icon', models.CharField(help_text="Font Awesome icon class, e.g., 'fas fa-home'", max_length=50)),
                ('description', models.TextField()),
                ('features', models.JSONField(help_text="List of features, e.g., ['Feature 1', 'Feature 2']")),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='Job title or position', max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.FloatField(default=5.0, help_text='Rating out of 5, e.g., 4.5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
