# Generated by Django 5.2.1 on 2025-06-18 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_created_at_profile_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order of display'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this team member on the website'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order for display (lower number first)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.FloatField(db_index=True, default=5.0, help_text='Rating out of 5, e.g., 4.5'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(db_index=True, help_text='Job title or position', max_length=100),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone'], name='core_profil_phone_e29419_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['title', 'created_at'], name='core_soluti_title_33f447_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['name', 'title'], name='core_teamme_name_f5267f_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['order', 'is_active'], name='core_teamme_order_12a0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['name', 'title', 'rating'], name='core_testim_name_276c3e_idx'),
        ),
    ]
